weechad confs and refactor setup

diff --git a/weechad-setup b/weechad-setup
--- a/weechad-setup
+++ b/weechad-setup
@@ -1,8 +1,10 @@
-#!/bin/sh
+#!/bin/bash
+
+# WeeChat configurator for Chads
+H=${HOME}/.weechad
 
 # LOGO
-chad_conf=""
-cat <<EOF |
+cat <<EOF
 ⣦⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠹⣿⠛⠿⠷⣶⣦⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⢿⣆⠀⠀⠀⠈⠉⠛⠿⢷⣶⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
@@ -11,7 +13,7 @@ cat <<EOF |
 ⠀⠀⠀⠸⣷⡀ configurator⠀⠀⠀⠉⠛⠿⣶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⢽⣧⠀⠀for Chads. ⠀⠀⠀⠀⠀⠀⠀⠉⠛⠻⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⢻⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⢷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠈⢿⡆⠀⠀Config in ~/.weechad⠀⠀⠀⠈⠙⠿⣤⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
+⠀⠀⠀⠀⠀⠈⢿⡆⠀⠀Setup in ~/.weechad⠀⠀⠀⠀⠈⠙⠿⣤⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠘⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠸⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣤⣤⣶⠶⠶⠶⠶⢶⣦⣤⣌⣙⢳⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⢿⣆⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣴⣶⠿⠟⠛⠛⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠻⢿⣧⣄⠀⠀⠀⠀⠀⠀
@@ -43,8 +45,138 @@ cat <<EOF |
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⡆⠀⠀⢀⣴⡾⠛⠁⠀⣀⣀⠤⠖⠊⠉⠀⠀⠀⠀⠀⠉⠁
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⡇⠀⣰⣿⣏⣀⣤⠴⠖⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 EOF
-while read -r line; do
-  chad_conf="$chad_conf;`printf '%s' "$line"`"
+
+err() { >&2 echo "🗿 $*"; }
+
+[ -d $H ] && {
+  err "Cannot overwrite: $H"
+  err "If you are really sure, delete and run again."
+  exit 1
+}
+
+command -v weechat || {
+  err "WeeChat not installed."
+  exit 1
+}
+
+# TODO: better version checking
+wcver=`weechat -v`
+echo ${wcver} | grep 4.4..  || {
+  err "WeeChat installed is old: ${wcver}"
+  err "Install from: https://weechat.org/download/weechat/stable"
+  exit 1
+}
+
+err "Chose a nickname?"
+read nick
+nick_conf="/set irc.server_default.nicks \"${nick},${nick}_,${nick}__,${nick}__\""
+
+# THEME
+theme_conf=""
+grep -v '^#' <<EOF |
+# requires: 256 color terminal
+/set weechat.look.buffer_notify_default message
+/set weechat.look.color_nick_offline on
+/set weechat.look.prefix_action " •"
+/set weechat.look.prefix_join "▬▶"
+/set weechat.look.prefix_network "▬▬"
+/set weechat.look.prefix_quit "◀▬"
+/set weechat.look.prefix_same_nick "⤷"
+/set weechat.look.prefix_suffix "│"
+/set weechat.look.read_marker_string "─"
+/set weechat.look.separator_horizontal ""
+/set weechat.look.scroll_page_percent 50
+/set weechat.color.chat_channel darkgray
+/set weechat.color.chat_delimiters darkgray
+/set weechat.color.chat_highlight_bg 60
+/set weechat.color.chat_host darkgray
+/set weechat.color.chat_nick darkgray
+/set weechat.color.chat_nick_colors "cyan,magenta,green,brown,lightblue,default,lightcyan,lightmagenta,lightgreen,blue,31,35,38,40,49,63,70,80,92,99,112,126,130,138,142,148,160,162,167,169,174,176,178,184,186,210,212,215,247"
+/set weechat.color.chat_nick_offline darkgray
+/set weechat.color.chat_prefix_action darkgray
+/set weechat.color.chat_prefix_join 24
+/set weechat.color.chat_prefix_network darkgray
+/set weechat.color.chat_prefix_quit 23
+/set weechat.color.chat_prefix_suffix 16
+/set weechat.color.chat_read_marker 16
+/set weechat.color.chat_tags darkgray
+/set weechat.color.chat_time darkgray
+/set weechat.color.chat_time_delimiters 234
+/set weechat.color.nicklist_away 244
+/set weechat.color.separator 16
+/set irc.look.color_nicks_in_names on
+/set irc.look.color_nicks_in_server_messages off
+/set irc.color.message_join darkgray
+/set irc.color.message_quit darkgray
+/set irc.color.reason_quit darkgray
+/set colorize_nicks.look.colorize_input on
+/set colorize_nicks.look.ignore_tags "irc_join,irc_part,irc_quit"
+/set script.color.text_bg_selected 234
+/trigger add url modifier weechat_print "${tg_tags} !~ irc_quit" ";[a-z]+://\S+;${color:228}${color:underline}${re:0}${color:reset};" ""
+/trigger add nick modifier weechat_print "${tg_tags} =~ irc_nick" ";is now known as;${color:darkgray}is now known as;" ""
+/trigger add disconnect modifier "weechat_print" "${tg_tags} !~ . && ${tg_buffer} !~ irc.server." ";irc: disconnected from server;${color:red}irc: disconnected from server;" ""
+EOF
+while read line; do
+  [ "$line" = "" ] && continue
+	theme_conf="$theme_conf;`printf '%s' "$line"`"
 done
-echo $chad_conf
-WEECHAT_HOME=$HOME/.weechad weechat -r "$chad_conf"
+
+script_conf=""
+grep -v '^#' <<EOF |
+/autosort helpers set monitors_buffers_first ${if:${buffer.full_name}!~^core\.(chan|high|news)mon$}
+/autosort rules insert 3 ${monitors_buffers_first}
+/set plugins.var.python.cmd_help.color_delimiters "*white"
+/set plugins.var.python.cmd_help.color_arguments "121"
+/set plugins.var.python.cmd_help.color_list "121"
+/set plugins.var.python.cmd_help.start_on_load "on"
+/set plugins.var.python.cmd_help.stop_on_enter "off"
+/cmd_help
+/highmon monitor
+/bar add highmon root top auto 0 4
+# /set weechat.bar.highmon.bar_lines 4
+EOF
+while read line
+do
+  [ "$line" = "" ] && continue
+  script_conf="$script_conf;`printf '%s' "$line"`"
+done
+
+server_conf=""
+grep -v '^#' <<EOF |
+/server add darkirc localhost/6667 -notls
+/server add libera localhost/6697 -tls
+EOF
+while read line
+do
+  [ "$line" = "" ] && continue
+  server_conf="$server_conf;`printf '%s' "$line"`"
+done
+
+pyscript() {
+  mkdir -p $H/python $H/python/autoload
+  curl -Ls https://weechat.org/files/scripts/${1} > $H/python/${1}
+  ln -s $H/python/${1} $H/python/autoload/${1}
+  #scripts="$scripts;/script load ${1};/script autoload ${1}"
+}
+plscript() {
+  mkdir -p $H/perl $H/perl/autoload
+  curl -Ls https://weechat.org/files/scripts/${1} > $H/perl/${1}
+  ln -sf $H/perl/${1} $H/perl/autoload/${1}
+  #scripts="$scripts;/script load ${1};/script autoload ${1}"
+}
+
+rm -rf $H
+mkdir -p $H
+
+pyscript autosort.py
+pyscript grep.py
+pyscript cmd_help.py
+pyscript colorize_nicks.py
+pyscript go.py
+pyscript collapse_channel.py
+
+plscript highmon.pl
+
+WEECHAT_HOME="$H" \
+weechat -a -r "$theme_conf" -r "$script_conf" -r "$server_conf" -r "/save;/quit;"
+err "Setup completed! Now copy ./weechad in your PATH"
